#!/bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M momoe.yoshida@my.jcu.edu.au
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=2:mem=64gb
cd $PBS_O_WORKDIR
# Add this to all of your scripts
shopt -s expand_aliases
source /etc/profile.d/modules.sh

# Output some useful information about
# the job we are running
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"
echo "Start time: $(date)"

# Load the container we want to use
# It is a good idea to always specify the version number 
module purge
module load matlab/2024a
module load gcc/10.5.0

echo "tar_date = $tar_date"

echo "YEAR=$YEAR DOY=$DOY"

# Run your code with useful debugging commands.
# <<'EOF': send the following commands to MATLAB as input
matlab -nodisplay -nosplash <<EOF
clear mex
dbstop if error
dbmex on

generate_oi_sst($YEAR,$DOY)

exit
EOF

echo "End time: $(date)"
